% pelicula(nombre, sinopsis, actores, duracion, idioma, año, enlaces, categoria, costo_obtencion, imagen)

pelicula('Rapidos y Furiosos 9', 'Dom Toretto lleva una vida tranquila con Letty y su hijo, el pequeño Brian, pero saben que el peligro siempre acecha.', 'Vin Diesel, Michelle Rodriguez, Tyrese Gibson', 145, 'Ingles', 2021, 'https://www.youtube.com/watch?v=q37Qo4_4rx0', 'Accion', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg').
pelicula('Godzilla vs. Kong', 'Godzilla y Kong, dos de las fuerzas mas poderosas de un planeta habitado por aterradoras criaturas, se enfrentan en un espectacular combate que sacude los cimientos de la humanidad.', 'Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall', 113, 'Ingles', 2021, 'https://www.youtube.com/watch?v=WFmgnu1RjBc', 'Accion', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/bnuC6hu7AB5dYW26A3o6NNLlIlE.jpg').
pelicula('Mortal Kombat', 'Un boxeador fracasado descubre un secreto familiar que lo lleva a un torneo místico llamado Mortal Kombat, donde se encuentra con un grupo de guerreros que luchan hasta la muerte para salvar los reinos del malvado hechicero Shang Tsung.', 'Lewis Tan, Jessica McNamee, Josh Lawson', 110, 'Ingles', 2021, 'https://www.youtube.com/watch?v=b-dfaJ1plvk', 'Accion', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/3tZwNIVrax1IV5BkGzWTYMmjYI5.jpg').
pelicula('El Escuadron Suicida', 'Bienvenido al infierno, tambien conocido como Belle Reve, la prision con la tasa de mortalidad mas alta de los Estados Unidos de America.', 'Margot Robbie, Idris Elba, John Cena', 132, 'Ingles', 2021, 'https://www.youtube.com/watch?v=S1F7WEVDBQ8', 'Accion', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/4AcvqhsaE26hshLKZhXmnlsIkcq.jpg').
pelicula('El Hombre Araña: Sin Camino a Casa', 'Peter Parker se encuentra en un aprieto cuando su identidad secreta es revelada.', 'Tom Holland, Zendaya, Benedict Cumberbatch', 130, 'Ingles', 2021, 'https://www.youtube.com/watch?v=cmI4XaaTbbA', 'Accion', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/1z7ZQhga4AcSkQNqEU3Tf9XpxoX.jpg').
pelicula('Iron Man', 'Tony Stark, un magnate industrial y genio inventor, construye un traje blindado y se convierte en Iron Man para luchar contra el mal.', 'Robert Downey Jr., Gwyneth Paltrow', 126, 'Ingles', 2008, 'https://www.disneyplus.com/video/8eaccf77-9e46-47f5-9b7a-fdc1e65cd1b4?distributionPartner=google', 'Accion', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/2Ms5bJuHPPzSuMGogEwyQu0UF7t.jpg').
pelicula('Captain America: The First Avenger', 'Steve Rogers, un joven voluntario del ejercito, se somete a un experimento y se convierte en el supersoldado conocido como Capitan America.', 'Chris Evans, Hayley Atwell', 124, 'Ingles', 2011, 'https://www.disneyplus.com/video/90aa1132-49e9-46a1-801c-4671ee788e75?distributionPartner=google', 'Accion', 4.99, 'https://basededatos.atrae.org/media/works/vSNxAJTlD0r02V9sPYpOjqDZXUK_nb6SkWK.jpg').
pelicula('Thor', 'Thor, el príncipe de Asgard, es desterrado a la Tierra y debe aprender a ser un verdadero heroe mientras enfrenta una amenaza sobrenatural.', 'Chris Hemsworth, Natalie Portman', 115, 'Ingles', 2011, 'https://www.disneyplus.com/video/ac837e8b-ab6d-46fc-8f34-86152fd905d8?distributionPartner=google', 'Accion', 4.99, 'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a0/Thor_-_Soundtrack_Alternativo.png/revision/latest?cb=20180925213221&path-prefix=es').
pelicula('The Avengers', 'Los superheroes de la Tierra, incluyendo a Iron Man, Capitan America, Thor y Hulk, se unen para enfrentar a Loki y su ejercito invasor.', 'Robert Downey Jr., Chris Evans, Chris Hemsworth', 143, 'Ingles', 2012, 'https://www.disneyplus.com/es-419/video/c05ea526-1378-4e4b-a38e-a29968cc0def?distributionPartner=google', 'Accion', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/tyKKKSvjEgDVQ6vtm8vzL5Zx06c.jpg').
pelicula('Guardians of the Galaxy', 'Peter Quill, tambien conocido como Star-Lord, lidera a un grupo de inadaptados cosmicos conocidos como los Guardianes de la Galaxia en una mision para salvar el universo.', 'Chris Pratt, Zoe Saldana', 121, 'Ingles', 2014, 'https://www.disneyplus.com/video/04667710-5866-4a77-be5d-a9f7265bdb5c?distributionPartner=google', 'Accion', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/lGR9yjcPctrIxNrnGBiXlEbM6nT.jpg').

pelicula('Frozen II', 'Elsa, Anna, Kristoff, Olaf y Sven se aventuran en lo desconocido del bosque encantado para descubrir la verdad sobre los poderes de Elsa y salvar su reino.', 'Idina Menzel, Kristen Bell, Jonathan Groff.', 103, 'Ingles', 2019, 'https://www.disneyplus.com/video/74351ae5-f6cd-4464-aeb6-8f4b10ca2649?distributionPartner=google', 'Animacion', 11.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/jnFCk7qGGWop2DgfnJXeKLZFuBq.jpg').
pelicula('Toy Story 4', 'Woody y Buzz Lightyear se embarcan en una aventura para rescatar a Forky, un nuevo juguete que se considera a sí mismo como basura.', 'Tom Hanks, Tim Allen, Annie Potts.', 100, 'Ingles', 2019, 'https://www.disneyplus.com/video/b8f267ef-53f4-4ac3-9997-e416f5981495?distributionPartner=google', 'Animacion', 12.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/61hlB1D6t1Ctbjk1YtW8V0Ij21Y.jpg').
pelicula('Spider-Man: Un nuevo universo', 'El joven Miles Morales se convierte en el nuevo Spider-Man y se une a otros heroes de diferentes universos para detener una amenaza que pone en peligro a todos los mundos.', 'Shameik Moore, Jake Johnson, Hailee Steinfeld.', 117, 'Ingles', 2018, 'https://www.disneyplus.com/es-419/video/a5f0b2c6-134f-4f23-bbbc-c848cac3cde9?distributionPartner=google', 'Animacion', 10.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/uAnWm2M8yeYXY7x1doLq0Oe5pVT.jpg').
pelicula('Zootopia', 'Judy Hopps, una conejita policía, se une a un astuto zorro llamado Nick Wilde para resolver un caso en la metropolis de animales conocida como Zootopia.', 'Ginnifer Goodwin, Jason Bateman, Idris Elba.', 108, 'Ingles', 2016, 'https://www.disneyplus.com/video/fb01a105-a47d-4016-930d-e01e03e17d83?distributionPartner=google', 'Animacion', 8.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/i3WnZpJkQYXXbSGplEGmyoyeskM.jpg').
pelicula('Los Increíbles 2', 'La familia de superheroes regresa en esta secuela, enfrentandose a nuevos desafíos mientras intentan equilibrar sus vidas normales con sus habilidades sobrehumanas.', 'Craig T. Nelson, Holly Hunter, Sarah Vowell.', 118, 'Ingles', 2018, 'https://www.disneyplus.com/video/f269b011-31b0-472c-9483-8de89ac78d00?distributionPartner=google', 'Animacion', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/tAIoOSidSE9Iyq8UK5G5gSiM0PK.jpg').
pelicula('Coco', 'Miguel, un niño aspirante a musico, se embarca en una extraordinaria aventura en la Tierra de los Muertos para desentrañar los secretos de su familia y cumplir su sueño.', 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt.', 105, 'Ingles', 2017, 'https://www.disneyplus.com/video/9f005b28-e0ce-417b-b007-1d26c90930c5?distributionPartner=google', 'Animacion', 11.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/oburjHqzOrTtDLYbLunKLwUHhk1.jpg').
pelicula('Moana', 'Moana, una valiente joven polinesia, se embarca en una peligrosa travesía en el oceano para salvar a su pueblo y descubrir su verdadera identidad.', 'Aulii Cravalho, Dwayne Johnson, Rachel House.', 107, 'Ingles', 2016, 'https://www.disneyplus.com/video/bad8a08e-a329-43ad-8ff9-0729884ececb?distributionPartner=google', 'Animacion', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/68j7CNWq1nrtN1EMck5icxHfwSt.jpg').
pelicula('Como entrenar a tu dragon', 'Hipo, un joven vikingo, se hace amigo de un dragon y juntos desafían las tradiciones de sus respectivas especies en busca de la convivencia pacífica.', 'Jay Baruchel, Gerard Butler, America Ferrera.', 98, 'Ingles', 2010, 'https://play.hbomax.com/feature/urn:hbo:feature:GWguO_gs4ma3CwgEAAAGy?source=googleHBOMAX&action=open', 'Animacion', 8.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/bXcRw7FL8QzUZOvY2fZdwDv5ymQ.jpg').
pelicula('Kung Fu Panda', 'Po, un torpe y gloton panda, se convierte en el elegido para convertirse en el Guerrero Dragon y defender el Valle de la Paz del malvado Tai Lung.', 'Jack Black, Dustin Hoffman, Angelina Jolie.', 92, 'Ingles', 2008, 'https://play.hbomax.com/feature/urn:hbo:feature:GXrR72QhID4ayhAEAAANa?source=googleHBOMAX&action=open', 'Animacion', 7.99, 'https://es.web.img3.acsta.net/pictures/16/03/04/13/44/418557.jpg').
pelicula('Shrek', 'Shrek, un ogro gruñon, se embarca en una mision para rescatar a la princesa Fiona y en el camino descubre el verdadero significado del amor y la amistad.', 'Mike Myers, Eddie Murphy, Cameron Diaz.', 90, 'Ingles', 2001, 'https://www.netflix.com/mx/title/60020686?source=35', 'Animacion', 6.99, 'https://mx.web.img3.acsta.net/pictures/14/03/06/10/13/369709.jpg').
pelicula('Space Jam: Una Nueva Era', 'Cuando LeBron y su hijo Dom quedan atrapados en un espacio digital por una I.A. renegada, LeBron debe llevarlos a casa a salvo liderando a Bugs, Lola Bunny y toda la pandilla de los Looney Tunes a la victoria sobre los campeones digitalizados de la I.A.', 'LeBron James, Don Cheadle, Khris Davis', 115, 'Ingles', 2021, 'https://play.hbomax.com/feature/urn:hbo:feature:GYOSUnARCGWWmcAEAAAAC?source=googleHBOMAX&action=open', 'Animacion', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg').

pelicula('Indiana Jones y los cazadores del arca perdida', 'Indiana Jones, un intrepido arqueologo, se embarca en una peligrosa mision para encontrar el Arca de la Alianza antes de que caiga en manos equivocadas.', 'Harrison Ford, Karen Allen, Paul Freeman.', 115, 'Ingles', 1981, 'https://www.disneyplus.com/video/ce972ed7-15f2-41e9-818c-3cdb8b197299?distributionPartner=google', 'Aventura', 9.99, 'https://static.wikia.nocookie.net/doblaje/images/a/a2/IndianaJonesLostArk.jpg/revision/latest?cb=20110412185959&path-prefix=es').
pelicula('Piratas del Caribe: La maldicion del Perla Negra', 'El capitan Jack Sparrow y el joven herrero Will Turner se unen para rescatar a la hija del gobernador y enfrentarse a los temibles piratas que buscan deshacer una maldicion.', 'Johnny Depp, Orlando Bloom, Keira Knightley.', 143, 'Ingles', 2003, 'https://www.disneyplus.com/video/66488bb4-9782-4a9a-b199-7b3f926c911d?distributionPartner=google', 'Aventura', 8.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/dHUZPilGRtQqsobeJYOMEvSLt4e.jpg').
pelicula('Jurassic Park', 'Un grupo de científicos es invitado a un parque tematico habitado por dinosaurios reales, pero pronto descubren que las cosas no saldran como esperaban.', 'Sam Neill, Laura Dern, Jeff Goldblum.', 127, 'Ingles', 1993, 'https://play.hbomax.com/page/urn:hbo:page:GYJlJDwG96Q_DwgEAAAA1:type:feature?source=googleHBOMAX&action=open', 'Aventura', 7.99, 'https://www.mubis.es/media/users/3724/286313/jurassic-park-the-ultimate-visual-history-portada-original.jpg').
pelicula('El Señor de los Anillos: La Comunidad del Anillo', 'Frodo Baggins, un hobbit, se embarca en un peligroso viaje para destruir un anillo maligno y salvar a la Tierra Media de la oscuridad.', 'Elijah Wood, Ian McKellen, Viggo Mortensen.', 178, 'Ingles', 2001, 'https://play.hbomax.com/feature/urn:hbo:feature:GXdu2ZAglVJuAuwEAADbA?source=googleHBOMAX&action=open', 'Aventura', 10.99, 'https://pics.filmaffinity.com/El_seanor_de_los_anillos_La_comunidad_del_anillo-423744684-large.jpg').
pelicula('Los Goonies', 'Un grupo de amigos descubre un antiguo mapa del tesoro y se embarca en una emocionante aventura para encontrar el tesoro y salvar sus hogares de la demolicion.', 'Sean Astin, Josh Brolin, Corey Feldman.', 114, 'Ingles', 1985, 'https://play.hbomax.com/page/urn:hbo:page:GXdu2RQwR0JuAuwEAADZ5:type:feature?source=googleHBOMAX&action=open', 'Aventura', 6.99, 'https://pbs.twimg.com/media/FEx5M9XXEAEGWm6.jpg:large').
pelicula('El Hobbit: Un viaje inesperado', 'Bilbo Bolson, un hobbit pacífico, se une a un grupo de enanos y al mago Gandalf en una peligrosa busqueda para recuperar un reino perdido de los enanos.', 'Martin Freeman, Ian McKellen, Richard Armitage.', 169, 'Ingles', 2012, 'https://www.primevideo.com/dp/amzn1.dv.gti.68b03eab-a511-45b2-b26c-b1d0d02ba867?autoplay=0&ref_=atv_cf_strg_wb', 'Aventura', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/2Also6fDCjczi6xEFYFOqiau3f7.jpg').
pelicula('Mad Max: Fury Road', 'En un mundo postapocalíptico, Max Rockatansky y Furiosa se unen en una frenetica persecucion para salvar a un grupo de mujeres de las garras de un tirano despiadado.', 'Tom Hardy, Charlize Theron, Nicholas Hoult.', 120, 'Ingles', 2015, 'https://www.primevideo.com/dp/amzn1.dv.gti.55901cd8-ab26-47ef-9a91-a474cd7696cd?autoplay=0&ref_=atv_cf_strg_wb', 'Aventura', 8.99, 'https://images.cdn1.buscalibre.com/fit-in/360x360/65/a5/65a575b8f0fc20665c0de8c7c17ba7c0.jpg').
pelicula('La busqueda', 'Un arqueologo y su hijo se embarcan en una busqueda para encontrar un tesoro oculto y desentrañar los enigmas dejados por los Padres Fundadores de Estados Unidos.', 'Nicolas Cage, Diane Kruger, Justin Bartha.', 131, 'Ingles', 2004, 'https://www.disneyplus.com/video/b74d5c19-6b60-48e9-8f21-a8c0b716077f?distributionPartner=google', 'Aventura', 7.99, 'https://es.web.img3.acsta.net/medias/nmedia/18/78/64/83/20071012.jpg').
pelicula('Avatar', 'Un veterano de guerra paraplejico es enviado a Pandora, un planeta habitado por una raza indígena y exuberante vida vegetal, donde se ve involucrado en un conflicto epico.', 'Sam Worthington, Zoe Saldana, Sigourney Weaver.', 162, 'Ingles', 2009, 'https://www.disneyplus.com/video/891bc89b-f746-47b3-8a7b-03135822d662?distributionPartner=google', 'Aventura', 11.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/tXmTHdrZgNsULqCbThK2Dt2X9Wt.jpg').
pelicula('King Kong', 'Un cineasta y su equipo viajan a una isla remota donde encuentran a King Kong, una criatura gigante que se enamora de una joven y desata el caos en Nueva York.', 'Naomi Watts, Jack Black, Adrien Brody.', 187, 'Ingles', 2005, 'https://www.netflix.com/watch/70021664?source=35', 'Aventura', 9.99, 'https://www.mubis.es/media/covers/2019/3917/king-kong-portada-l_cover.jpg').

pelicula('El Conjuro 3: El Diablo Me Obligo a Hacerlo', 'El matrimonio Warren investiga un caso de posesion demoníaca que termina en un asesinato.', 'Vera Farmiga, Patrick Wilson, Ruairi OConnor', 112, 'Ingles', 2021, 'https://play.hbomax.com/feature/urn:hbo:feature:GYOYX9gphVFOLNgEAAAQR?source=googleHBOMAX&action=open', 'Terror', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/x4jUJ0fF60SSOeUUTkaRtmnDvwG.jpg').
pelicula('Un Lugar en Silencio 2', 'La familia Abbott ahora debe enfrentar los terrores del mundo exterior mientras luchan por sobrevivir en silencio.', 'Emily Blunt, Cillian Murphy, Millicent Simmonds', 97, 'Ingles', 2021, 'https://www.youtube.com/watch?v=b3c1LFBosEY', 'Terror', 4.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/2ixiP0rHnbxD3VMCv8WNkmSbzZp.jpg').
pelicula('El Exorcista', 'Una niña poseída por una entidad demoníaca lleva a un sacerdote a enfrentarse a su fe y a luchar contra el mal para salvarla.', 'Linda Blair, Ellen Burstyn, Max von Sydow.', 122, 'Ingles', 1973, 'https://www.youtube.com/watch?v=czfJ85_x-w4', 'Terror', 9.99, 'https://pics.filmaffinity.com/El_exorcista-330405097-large.jpg').
pelicula('El Resplandor', 'Un escritor en busca de inspiracion se convierte en cuidador de un hotel aislado, pero la presencia maligna del lugar desencadena su descenso a la locura.', 'Jack Nicholson, Shelley Duvall, Danny Lloyd.', 144, 'Ingles', 1980, 'https://www.youtube.com/watch?v=6TVsb5HmX50', 'Terror', 8.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/p9hqo2JWhBytLxskz4FBKcP2e1k.jpg').
pelicula('El Conjuro', 'Basada en hechos reales, una pareja de investigadores paranormales se enfrenta a una entidad maligna que amenaza a una familia en su hogar.', 'Vera Farmiga, Patrick Wilson, Lili Taylor.', 112, 'Ingles', 2013, 'https://www.youtube.com/watch?v=bNfCEI9Ro3E', 'Terror', 7.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/x4jUJ0fF60SSOeUUTkaRtmnDvwG.jpg').
pelicula('Psicosis', 'Una secretaria en fuga se refugia en un motel regentado por un joven tímido y su dominante madre, desencadenando una serie de eventos aterradores.', 'Anthony Perkins, Janet Leigh, Vera Miles.', 109, 'Ingles', 1960, 'https://play.hbomax.com/page/urn:hbo:page:GYIBRCgdPHKTDGQEAAADp:type:feature?source=googleHBOMAX&action=open', 'Terror', 6.99, 'https://www.mubis.es/media/covers/1307/1521/psicosis-portada-original.jpg').
pelicula('El Aro', 'Una periodista investiga una misteriosa cinta de video que supuestamente causa la muerte de quien la ve en siete días.', 'Naomi Watts, Martin Henderson, David Dorfman.', 115, 'Ingles', 2002, 'https://www.youtube.com/watch?v=fTq9cSj6sSE', 'Terror', 7.99, 'https://www.ecartelera.com/carteles/16300/16312/001_m.jpg').
pelicula('El Exorcismo de Emily Rose', 'Basada en una historia real, un sacerdote se enfrenta a un juicio por homicidio debido a la muerte de una joven durante un exorcismo.', 'Laura Linney, Tom Wilkinson, Jennifer Carpenter.', 119, 'Ingles', 2005, 'https://www.youtube.com/watch?v=AZXpMOPpQ74', 'Terror', 8.99, 'https://es.web.img3.acsta.net/medias/nmedia/18/89/76/11/20065517.jpg').
pelicula('El Proyecto de la Bruja de Blair', 'Un grupo de estudiantes de cine desaparece mientras investiga la leyenda de una bruja en un bosque, dejando atras su inquietante material grabado.', 'Heather Donahue, Michael C. Williams, Joshua Leonard.', 81, 'Ingles', 1999, 'https://play.hbomax.com/page/urn:hbo:page:GWSMCgA0RkoqXwgEAAACA:type:feature?source=googleHBOMAX&action=open', 'Terror', 6.99, 'https://pics.filmaffinity.com/El_proyecto_de_la_bruja_de_Blair-169732125-large.jpg').
pelicula('Actividad Paranormal', 'Una pareja documenta la presencia de fenomenos paranormales en su hogar, desatando una escalada de sucesos aterradores.', 'Katie Featherston, Micah Sloat.', 86, 'Ingles', 2007, 'https://www.youtube.com/watch?v=gbYt5U3zL-M', 'Terror', 6.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/5vtmCckiI4fsYZkjmHJc1CZmVqH.jpg').

pelicula('Loco por Mary', 'Un hombre se embarca en un viaje desastroso para encontrar a su amor de la escuela secundaria y se encuentra enredado en situaciones hilarantes y absurdas.', 'Ben Stiller, Cameron Diaz, Matt Dillon.', 119, 'Ingles', 1998, 'https://www.starplus.com/video/25063712-4c8f-4631-a6ff-4a1eb5d936b5?distributionPartner=google', 'Comedia', 6.99, 'https://i.pinimg.com/originals/a3/87/a2/a387a27d38d9b506940334b8768e62e1.jpg').
pelicula('Superbad', 'Dos amigos adolescentes se embarcan en una mision epica para comprar alcohol y conquistar a las chicas de sus sueños antes de graduarse de la escuela secundaria.', 'Jonah Hill, Michael Cera, Christopher Mintz-Plasse.', 113, 'Ingles', 2007, 'https://www.youtube.com/watch?v=wk5qHI63YAs', 'Comedia', 7.99, 'https://images.coveralia.com/audio/b/BSO_Supersalidos_(Superbad)--Frontal.jpg').
pelicula('Chicas pesadas', 'Una joven ingenua se infiltra en un grupo popular de chicas de la escuela secundaria y descubre los desafíos y la crueldad de la jerarquía social.', 'Lindsay Lohan, Rachel McAdams, Tina Fey.', 97, 'Ingles', 2004, 'https://www.youtube.com/watch?v=bQrNh310fog', 'Comedia', 6.99, 'https://mx.web.img3.acsta.net/r_1280_720/medias/nmedia/18/89/87/42/20070835.jpg').
pelicula('El Gran Lebowski', 'Un hombre llamado El Nota se ve envuelto en una serie de eventos extraños y comicos despues de que lo confunden con un millonario del mismo nombre.', 'Jeff Bridges, John Goodman, Julianne Moore.', 117, 'Ingles', 1998, 'https://www.youtube.com/watch?v=O4VmdpndCes', 'Comedia', 8.99, 'https://es.web.img3.acsta.net/r_1280_720/pictures/14/03/27/13/54/440071.jpg').
pelicula('Zoolander', 'Un famoso modelo masculino es reclutado para detener a un grupo de conspiradores que planean asesinar al Primer Ministro de Malasia.', 'Ben Stiller, Owen Wilson, Will Ferrell.', 90, 'Ingles', 2001, 'https://www.youtube.com/watch?v=QqBCYrL_sx8', 'Comedia', 7.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/zjQD0PNPdH6fvBgT6WDPXq03ckz.jpg').
pelicula('El Diario de Bridget Jones', 'Una mujer en sus 30 años busca el amor y lucha contra los desafíos de la vida mientras registra sus experiencias en su diario personal.', 'Renee Zellweger, Colin Firth, Hugh Grant.', 97, 'Ingles', 2001, 'https://www.youtube.com/watch?v=n-j2qoOnCQ8', 'Comedia', 6.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/77XNNSI3MCoi3mMPgGmemAt5ulN.jpg').
pelicula('La Mascara', 'Un hombre tímido encuentra una mascara magica que lo transforma en un ser con habilidades increíbles, pero tambien desata su lado mas salvaje.', 'Jim Carrey, Cameron Diaz, Peter Riegert.', 101, 'Ingles', 1994, 'https://www.youtube.com/watch?v=ZDPXW9jnbvg', 'Comedia', 8.99, 'https://www.mubis.es/media/covers/1487/1942/la-mascara-portada-original.jpg').
pelicula('Resacon en Las Vegas', 'Despues de una noche de fiesta desenfrenada en Las Vegas, un grupo de amigos despierta sin recordar lo sucedido y deben reconstruir los eventos caoticos.', 'Bradley Cooper, Ed Helms, Zach Galifianakis.', 100, 'Ingles', 2009, 'https://www.youtube.com/watch?v=bi9um_nLDPA', 'Comedia', 7.99, 'https://www.mubis.es/media/covers/1624/2457/resacon-en-las-vegas-portada-original.jpg').
pelicula('Amelie', 'Una joven inocente y soñadora se embarca en una mision para mejorar la vida de las personas que la rodean mientras busca su propia felicidad.', 'Audrey Tautou, Mathieu Kassovitz, Rufus.', 122, 'Ingles', 2001, 'https://www.youtube.com/watch?v=FpvoBLSi1iM', 'Comedia', 9.99, 'https://es.web.img2.acsta.net/pictures/21/06/18/12/28/5014869.jpg').
pelicula('¡Olvidate de mi!', 'Despues de una dolorosa ruptura, un hombre decide borrar todos los recuerdos de su exnovia, pero descubre que algunos recuerdos son difíciles de olvidar.', 'Jim Carrey, Kate Winslet, Kirsten Dunst.', 122, 'Ingles', 2004, 'https://www.primevideo.com/dp/amzn1.dv.gti.26bb4b1c-da6c-58d1-5389-d51db774ba2b?autoplay=0&ref_=atv_cf_strg_wb', 'Comedia', 7.99, 'https://www.mubis.es/media/covers/1279/1461/olvidate-de-mi-portada-original.jpg').

pelicula('El Padrino', 'El hijo de un poderoso jefe de la mafia se ve obligado a tomar las riendas de la familia criminal despues de un intento de asesinato.', 'Marlon Brando, Al Pacino, James Caan.', 177, 'Ingles', 1972, 'https://www.youtube.com/watch?v=ELlGMAcZ3Cs', 'Drama', 9.99, 'https://pics.filmaffinity.com/El_padrino-109363915-large.jpg').
pelicula('El Padrino II', 'El hijo de un poderoso jefe de la mafia se ve obligado a tomar las riendas de la familia criminal despues de un intento de asesinato.', 'Al Pacino, Robert De Niro, Robert Duvall.', 202, 'Ingles', 1974, 'https://www.youtube.com/watch?v=DQ442Bn1Z6w', 'Drama', 9.99, 'https://es.web.img3.acsta.net/medias/nmedia/18/68/09/69/20420487.jpg').
pelicula('El Padrino III', 'Un jefe de la mafia retirado se ve obligado a volver a la vida criminal para proteger a su familia de sus enemigos.', 'Al Pacino, Diane Keaton, Andy García.', 170, 'Ingles', 1990, 'https://www.primevideo.com/dp/amzn1.dv.gti.ccac5a1d-08d4-5f85-3c72-2369147d24e2?autoplay=0&ref_=atv_cf_strg_wb', 'Drama', 9.99, 'https://m.media-amazon.com/images/I/71ZzIWa8wvL._AC_SY445_.jpg').
pelicula('Titanic', 'Un joven artista y una mujer de clase alta se enamoran a bordo del Titanic, pero su romance se ve amenazado por el tragico destino del barco.', 'Leonardo DiCaprio, Kate Winslet, Billy Zane.', 194, 'Ingles', 1997, 'https://www.starplus.com/video/70223d15-e3e4-4114-84c6-8a7d371cbcd2?distributionPartner=google', 'Drama', 9.99, 'https://img.gruporeforma.com/imagenes/630x945/4/854/3853436.jpg').
pelicula('El Renacido', 'Un trampero herido es abandonado por su equipo despues de ser atacado por un oso, y se embarca en una odisea de venganza a traves del desierto helado.', 'Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson.', 156, 'Ingles', 2015, 'https://play.hbomax.com/feature/urn:hbo:feature:GV40MagYuk4qFrwEAAABf?source=googleHBOMAX&action=open', 'Drama', 7.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/k3Jh7J5GGMx1lmr7qmynRxOvOK5.jpg').
pelicula('La Lista de Schindler', 'Durante la Segunda Guerra Mundial, un empresario aleman salva a mas de mil judíos polacos de los campos de concentracion nazis.', 'Liam Neeson, Ben Kingsley, Ralph Fiennes.', 195, 'Ingles, Aleman, Hebreo, Polaco', 1993, 'https://www.youtube.com/watch?v=vFaHpU3YPFs', 'Drama', 8.99, 'https://m.media-amazon.com/images/I/91ffJuaD3-L._AC_SY679_.jpg').
pelicula('El Club de la Pelea', 'Un hombre aburrido y desilusionado forma un club de pelea clandestino como una forma de escape, pero pronto se ve atrapado en una espiral violenta y caotica.', 'Brad Pitt, Edward Norton, Helena Bonham Carter.', 139, 'Ingles', 1999, 'https://play.hbomax.com/page/urn:hbo:page:GXSycSQud4r29bAEAAA10:type:feature?source=googleHBOMAX&action=open', 'Drama', 7.99, 'https://c8.alamy.com/compes/2k8pwef/poster-del-club-de-lucha-2k8pwef.jpg').
pelicula('Forrest Gump', 'La vida extraordinaria de Forrest Gump, un hombre de inteligencia limitada pero con un corazon puro, quien se encuentra involucrado en importantes eventos historicos.', 'Tom Hanks, Robin Wright, Gary Sinise.', 142, 'Ingles', 1994, 'https://www.youtube.com/watch?v=MgqzfiiA70g', 'Drama', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/azV6hV99lYkdhydsQbJCI6FqMl4.jpg').
pelicula('El Silencio de los Corderos', 'Una joven agente del FBI busca la ayuda de un peligroso asesino en serie encarcelado para atrapar a otro asesino en serie que esta aterrorizando al país.', 'Jodie Foster, Anthony Hopkins, Scott Glenn.', 118, 'Ingles', 1991, 'https://www.clarovideo.com/mexico/watch/1039841', 'Drama', 8.99, 'https://www.surrealismstore.com/imagenes/poridentidad?identidad=0d5783b5-edbe-4da3-8669-50b74f992b5f&ancho=850&alto=').
pelicula('La Vida es Bella', 'Un padre amoroso utiliza su imaginacion y humor para proteger a su hijo de los horrores de un campo de concentracion durante el Holocausto.', 'Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini.', 116, 'Italiano', 1997, 'https://www.youtube.com/watch?v=e-Z062tRdbQ', 'Drama', 7.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/kfRQ4X9z5eOXD1NbYR0JqlOlidJ.jpg').

pelicula('Orgullo y Prejuicio', 'En la Inglaterra del siglo XIX, una joven inteligente y energica se debate entre el amor y las convenciones sociales cuando conoce a un apuesto y enigmatico caballero.', 'Keira Knightley, Matthew Macfadyen, Donald Sutherland.', 129, 'Ingles', 2005, 'enlace', 'Romance', 7.99, 'https://images.cdn3.buscalibre.com/fit-in/360x360/46/6b/466b0b47e932561b186c56358acbe55e.jpg').
pelicula('Titanic', 'Un joven artista y una mujer de clase alta se enamoran a bordo del Titanic, pero su romance se ve amenazado por el tragico destino del barco.', 'Leonardo DiCaprio, Kate Winslet, Billy Zane.', 194, 'Ingles', 1997, 'https://www.starplus.com/video/70223d15-e3e4-4114-84c6-8a7d371cbcd2?distributionPartner=google', 'Romance', 9.99, 'https://img.gruporeforma.com/imagenes/630x945/4/854/3853436.jpg').
pelicula('Romeo y Julieta', 'La legendaria historia de amor entre dos jovenes de familias enemigas, cuyo amor prohibido desencadena una serie de tragicos acontecimientos.', 'Leonardo DiCaprio, Claire Danes, John Leguizamo.', 120, 'Ingles', 1996, 'https://www.starplus.com/video/667fe101-60ac-464a-9d9b-0510b4a9e8d4?distributionPartner=google', 'Romance', 8.99, 'https://images.cdn2.buscalibre.com/fit-in/360x360/27/e9/27e92f0d8b351aef49730410ab4da17d.jpg').
pelicula('La La Land', 'Un pianista y una aspirante a actriz se enamoran en Los angeles mientras persiguen sus sueños en una ciudad llena de esperanzas y desilusiones.', 'Ryan Gosling, Emma Stone, John Legend.', 128, 'Ingles', 2016, 'https://play.hbomax.com/page/urn:hbo:page:GWW-7cgsXAj3DEAEAAABt:type:feature?source=googleHBOMAX&action=open', 'Romance', 7.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/7pFsAaJmiOppVHcldBzg8JKBHwe.jpg').
pelicula('Diario de una Pasion', 'Una historia de amor eterno entre un joven humilde y una joven adinerada en la decada de 1940, que se enfrenta a obstaculos y desafíos a lo largo de los años.', 'Ryan Gosling, Rachel McAdams, James Garner.', 123, 'Ingles', 2004, 'https://play.hbomax.com/feature/urn:hbo:feature:GX-nzMw1oyZHDwwEAAAN3?source=googleHBOMAX&action=open', 'Romance', 6.99, 'https://i.pinimg.com/236x/8d/16/6c/8d166c3fdb98a466e2e25ac81f57d899--sparks-movies-romance-movies.jpg').
pelicula('Bajo la Misma Estrella', 'Dos adolescentes con enfermedades terminales se conocen y se enamoran, viviendo momentos intensos y emotivos mientras enfrentan los desafíos de la vida y la muerte.', 'Shailene Woodley, Ansel Elgort, Nat Wolff.', 126, 'Ingles', 2014, 'https://www.disneyplus.com/video/d105c412-6259-4ec8-b365-4185d07733f9?distributionPartner=google', 'Romance', 7.99, 'https://silverlibros.com/wp-content/uploads/2022/05/9786073123198-bajo-la-misma-estrella.jpg').
pelicula('Casablanca', 'En la Casablanca ocupada por los nazis durante la Segunda Guerra Mundial, un antiguo amante se reencuentra con un hombre que ahora debe elegir entre el amor y el deber.', 'Humphrey Bogart, Ingrid Bergman, Paul Henreid.', 102, 'Ingles', 1942, 'https://www.youtube.com/watch?v=4xtpBk-ESBc', 'Romance', 8.99, 'https://www.mubis.es/media/covers/2168/4584/casablanca-portada-l_cover.jpg').
pelicula('El Cuaderno de Noah', 'Una pareja de jovenes se enamora durante el verano, pero son separados por circunstancias adversas. Años mas tarde, se reencuentran y el amor resurge.', 'Ryan Gosling, Rachel McAdams, James Garner.', 123, 'Ingles', 2004, 'https://www.youtube.com/watch?v=Xi-op_tBItE', 'Romance', 7.99, 'https://m.media-amazon.com/images/I/51LwumI2B3L.jpg').
pelicula('Antes del Amanecer', 'Dos jovenes se conocen en un tren y deciden pasar un día juntos en Viena, compartiendo conversaciones profundas y descubriendo una conexion especial.', 'Ethan Hawke, Julie Delpy.', 101, 'Ingles', 1995, 'https://www.youtube.com/watch?v=G3kIsyIC-vE', 'Romance', 6.99, 'https://www.covercaratulas.com/ode/mini/divx-18088-a.jpg').
pelicula('Crepusculo', 'Una adolescente se enamora de un misterioso y atractivo vampiro, desencadenando una historia de amor prohibido entre dos mundos diferentes.', 'Kristen Stewart, Robert Pattinson, Taylor Lautner.', 122, 'Ingles', 2008, 'https://www.youtube.com/watch?v=5WaDLcWZvZ4', 'Romance', 9.99, 'https://images.coveralia.com/audio/b/BSO_Crepusculo_(Twilight)_(Score)--Frontal.jpg').

pelicula('El Señor de los Anillos: El Retorno del Rey', 'Los ejercitos de Sauron han atacado Minas Tirith, la capital de Gondor. Ahora, el destino de la Tierra Media esta en manos de dos pequeños hobbits.', 'Elijah Wood, Viggo Mortensen, Ian McKellen.', 201, 'Ingles', 2003, 'enlahttps://www.youtube.com/watch?v=GmPKXyzmQnUce', 'Fantasía', 9.99, 'https://static.wikia.nocookie.net/bibliotecadelatierramedia/images/1/16/Elretornodelrey.jpg/revision/latest?cb=20130713130831&path-prefix=es').
pelicula('El Señor de los Anillos: La Comunidad del Anillo', 'Un hobbit de la Comarca y ocho compañeros emprenden un viaje para destruir el poderoso Anillo unico y salvar la Tierra Media del Señor Oscuro Sauron.', 'Elijah Wood, Ian McKellen, Orlando Bloom.', 178, 'Ingles', 2001, 'https://www.youtube.com/watch?v=Uha4oOsdbp4', 'Fantasía', 9.99, 'https://lavozenoffdotnet.files.wordpress.com/2012/12/el_senor_de_los_anillos_la_comunidad_del_anillo-caratula.jpg?w=640').
pelicula('El Señor de los Anillos: Las Dos Torres', 'Frodo y Sam continuan su viaje hacia Mordor para destruir el Anillo unico. Mientras tanto, Aragorn y sus compañeros se preparan para la batalla contra las fuerzas de Sauron.', 'Elijah Wood, Ian McKellen, Viggo Mortensen.', 179, 'Ingles', 2002, 'https://www.youtube.com/watch?v=UYSbV6mLX08', 'Fantasía', 9.99, 'https://images-na.ssl-images-amazon.com/images/S/pv-target-images/79777590897729b0ef23cc0211700cd0cf18a33875dfdbc6e5c52c08053989c4._RI_TTW_.jpg').
pelicula('Harry Potter y la Piedra Filosofal', 'Un niño huerfano es aceptado en la Escuela de Magia y Hechicería de Hogwarts, donde se hace amigo de un joven y sus dos compañeros, y se enfrenta a un malvado mago.', 'Daniel Radcliffe, Rupert Grint, Richard Harris.', 152, 'Ingles', 2001, 'https://www.youtube.com/watch?v=sK1ZkF45A1k', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/7xXJ15VEf7G9GdAuV1dO769yC73.jpg').
pelicula('Harry Potter y la Camara Secreta', 'Harry ignora las advertencias de un elfo domestico y regresa a Hogwarts para comenzar su segundo año. Allí, descubre que la Camara de los Secretos ha sido abierta.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 161, 'Ingles', 2002, 'https://www.youtube.com/watch?v=hTei_FyQ29U', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/bhCfAzeMMg7GyLDT11yVM2i1NPh.jpg').
pelicula('Harry Potter y el Prisionero de Azkaban', 'Harry Potter debe enfrentarse a un peligroso fugitivo y a los Dementores, guardianes de la prision de Azkaban, pero tambien descubre una gran verdad sobre su pasado.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 142, 'Ingles', 2004, 'https://www.youtube.com/watch?v=j6cmpvR4p2Y', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/wF9aoo4YZmpKP4bZPSy4Zwwek6G.jpg').
pelicula('Harry Potter y el Caliz de Fuego', 'Harry Potter se enfrenta a un dragon, a un mago oscuro y a un laberinto magico, pero su mayor desafío es la Copa de los Tres Magos.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 157, 'Ingles', 2005, 'enlace', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/6Cn5Lx9kqhXzTNV5QXwZ3RW5pBg.jpg').
pelicula('Harry Potter y la Orden del Fenix', 'Harry Potter se enfrenta a un peligroso mago que ha regresado de entre los muertos y esta decidido a dominar el mundo magico.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 139, 'Ingles', 2007, 'enlace', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/z5bL1z1ZOAKBkvbOhVQp6GfBv4u.jpg').
pelicula('Harry Potter y el Misterio del Príncipe', 'Harry Potter y Dumbledore intentan descubrir la razon por la que Voldemort quiere encontrar la varita del poderoso mago Grindelwald.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 153, 'Ingles', 2009, 'enlace', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/ttdilnbDffymQd7Tkp7pP9W8h05.jpg').
pelicula('Harry Potter y las Reliquias de la Muerte: Parte 1', 'Harry, Ron y Hermione deben encontrar los Horrocruxes restantes de Voldemort para poner fin a su reinado de terror.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 146, 'Ingles', 2010, 'enlace', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/fYyoJ4Yadk0MCBHZPFrgvMDl50o.jpg').
pelicula('Harry Potter y las Reliquias de la Muerte: Parte 2', 'Harry, Ron y Hermione continuan su busqueda para encontrar y destruir los Horrocruxes de Voldemort, pero cuando Voldemort descubre sus planes, la batalla final comienza.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 130, 'Ingles', 2011, 'enlace', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/aM1TuUiPtV8OAZyu61CTdy9Ymtk.jpg').
pelicula('El Hobbit: Un Viaje Inesperado', 'Bilbo Bolson, un hobbit pacífico, se une a un grupo de enanos para recuperar su tesoro de las garras de un dragon.', 'Martin Freeman, Ian McKellen, Richard Armitage.', 169, 'Ingles', 2012, 'enlace', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/2Also6fDCjczi6xEFYFOqiau3f7.jpg').
pelicula('El Hobbit: La Desolacion de Smaug', 'Bilbo y los enanos continuan su busqueda para recuperar su tesoro de las garras del dragon Smaug.', 'Martin Freeman, Ian McKellen, Richard Armitage.', 161, 'Ingles', 2013, 'enlace', 'Fantasía', 9.99, 'https://image.tmdb.org/t/p/w185_and_h278_bestv2/m8uQ5swzBLRyY19UwqCsVK2fM7C.jpg').
pelicula('El Hobbit: La Batalla de los Cinco Ejercitos', 'Bilbo y los enanos se enfrentan a Smaug, mientras que otro ejercito se acerca a Erebor.', 'Martin Freeman, Ian McKellen, Richard Armitage.', 144, 'Ingles', 2014, 'enlace', 'Fantasía', 9.99, 'https://i.blogs.es/4a1bfb/hobbit_3_batalla_de_los_cinco_ejercitos_poster_final/450_1000.jpg').

imprimir_peliculas :-
    pelicula(Nombre, Sinopsis, Actores, Duracion, Idioma, Anio, Enlaces, Categoria, Costo, Imagen),
    write(Nombre), nl,
    write(Sinopsis), nl,
    write(Actores), nl,
    write(Duracion), nl,
    write(Idioma), nl,
    write(Anio), nl,
    write(Enlaces), nl,
    write(Categoria), nl,
    write(Costo), nl,
    write(Imagen), nl,
    nl,
    fail.

imprimir_peliculas_categoria(Categoria) :-
    pelicula(Nombre, Sinopsis, Actores, Duracion, Idioma, Anio, Enlaces, Categoria, Costo, Imagen),
    write(Nombre), nl,
    write(Sinopsis), nl,
    write(Actores), nl,
    write(Duracion), nl,
    write(Idioma), nl,
    write(Anio), nl,
    write(Enlaces), nl,
    write(Categoria), nl,
    write(Costo), nl,
    write(Imagen), nl,
    nl,
    fail.

imprimir_peliculas_nombre(Nombre) :-
    pelicula(Nombre, Sinopsis, Actores, Duracion, Idioma, Anio, Enlaces, Categoria, Costo, Imagen),
    write(Nombre), nl,
    write(Sinopsis), nl,
    write(Actores), nl,
    write(Duracion), nl,
    write(Idioma), nl,
    write(Anio), nl,
    write(Enlaces), nl,
    write(Categoria), nl,
    write(Costo), nl,
    write(Imagen), nl,
    nl,
    fail.

imprimir_peliculas_estrenos :-
    pelicula(Nombre, Sinopsis, Actores, Duracion, Idioma, Anio, Enlaces, Categoria, Costo, Imagen),
    Anio >= 2020,
    write(Nombre), nl,
    write(Sinopsis), nl,
    write(Actores), nl,
    write(Duracion), nl,
    write(Idioma), nl,
    write(Anio), nl,
    write(Enlaces), nl,
    write(Categoria), nl,
    write(Costo), nl,
    write(Imagen), nl,
    nl,
    fail.

imprimir_peliculas_recomendadas(Categoria) :-
    imprimir_peliculas_recomendadas(Categoria, []).

imprimir_peliculas_recomendadas(_, PeliculasImpresas) :-
    length(PeliculasImpresas, Length),
    Length >= 3. % Se detiene la ejecucion despues de tres películas.

imprimir_peliculas_recomendadas(Categoria, PeliculasImpresas) :-
    pelicula(Nombre, Sinopsis, Actores, Duracion, Idioma, Anio, Enlaces, Categoria, Costo, Imagen),
    \+ member(pelicula(Nombre, _, _, _, _, _, _, _, _), PeliculasImpresas),
    write(Nombre), nl,
    write(Sinopsis), nl,
    write(Actores), nl,
    write(Duracion), nl,
    write(Idioma), nl,
    write(Anio), nl,
    write(Enlaces), nl,
    write(Categoria), nl,
    write(Costo), nl,
    write(Imagen), nl,
    nl,
    imprimir_peliculas_recomendadas(Categoria, [pelicula(Nombre, _, _, _, _, _, _, _, _) | PeliculasImpresas]).