% pelicula(nombre, sinopsis, actores, duracion, idioma, año, enlaces, categoria, costo_obtencion)

pelicula('Infiltrados Mortales', 'Un agente encubierto debe desmantelar una peligrosa organización criminal desde adentro.', 'Jason Statham, Charlize Theron, Chris Hemsworth', 120, 'Inglés', 2022, '', 'Acción', 4.99).
pelicula('Rápidos y Furiosos 9', 'Dom Toretto lleva una vida tranquila con Letty y su hijo, el pequeño Brian, pero saben que el peligro siempre acecha.', 'Vin Diesel, Michelle Rodriguez, Tyrese Gibson', 145, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('Godzilla vs. Kong', 'Godzilla y Kong, dos de las fuerzas más poderosas de un planeta habitado por aterradoras criaturas, se enfrentan en un espectacular combate que sacude los cimientos de la humanidad.', 'Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall', 113, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('Mortal Kombat', 'Un boxeador fracasado descubre un secreto familiar que lo lleva a un torneo místico llamado Mortal Kombat, donde se encuentra con un grupo de guerreros que luchan hasta la muerte para salvar los reinos del malvado hechicero Shang Tsung.', 'Lewis Tan, Jessica McNamee, Josh Lawson', 110, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('El Escuadrón Suicida', 'Bienvenido al infierno, también conocido como Belle Reve, la prisión con la tasa de mortalidad más alta de los Estados Unidos de América.', 'Margot Robbie, Idris Elba, John Cena', 132, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('La Venganza Implacable', 'Un exagente especial busca vengarse de quienes mataron a su familia.', 'Liam Neeson, Jennifer Garner, Mark Wahlberg', 110, 'Inglés', 2019, '', 'Acción', 3.99).
pelicula('Código de Honor', 'Un soldado de élite se embarca en una misión para desenmascarar una conspiración gubernamental.', 'Vin Diesel, Michelle Rodriguez, Samuel L. Jackson', 115, 'Inglés', 2017, '', 'Acción', 2.99).
pelicula('Operación Encubierta', 'Un grupo de agentes encubiertos debe detener un complot terrorista antes de que sea demasiado tarde.', 'Tom Cruise, Scarlett Johansson, Idris Elba', 125, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('Misión Peligrosa', 'Un equipo de élite es enviado en una misión suicida para rescatar a un rehén de un poderoso criminal.', 'Dwayne Johnson, Emily Blunt, Tom Hardy', 130, 'Inglés', 2023, '', 'Acción', 3.99).
pelicula('El Hombre Araña: Sin Camino a Casa', 'Peter Parker se encuentra en un aprieto cuando su identidad secreta es revelada.', 'Tom Holland, Zendaya, Benedict Cumberbatch', 130, 'Inglés', 2021, '', 'Acción', 4.99).

pelicula('Frozen II', 'Elsa, Anna, Kristoff, Olaf y Sven se aventuran en lo desconocido del bosque encantado para descubrir la verdad sobre los poderes de Elsa y salvar su reino.', 'Idina Menzel, Kristen Bell, Jonathan Groff.', 103, 'Inglés', 2019, '', 'Animación', 11.99).
pelicula('Toy Story 4', 'Woody y Buzz Lightyear se embarcan en una aventura para rescatar a Forky, un nuevo juguete que se considera a sí mismo como basura.', 'Tom Hanks, Tim Allen, Annie Potts.', 100, 'Inglés', 2019, '', 'Animación', 12.99).
pelicula('Spider-Man: Un nuevo universo', 'El joven Miles Morales se convierte en el nuevo Spider-Man y se une a otros héroes de diferentes universos para detener una amenaza que pone en peligro a todos los mundos.', 'Shameik Moore, Jake Johnson, Hailee Steinfeld.', 117, 'Inglés', 2018, '', 'Animación', 10.99).
pelicula('Zootopia', 'Judy Hopps, una conejita policía, se une a un astuto zorro llamado Nick Wilde para resolver un caso en la metrópolis de animales conocida como Zootopia.', 'Ginnifer Goodwin, Jason Bateman, Idris Elba.', 108, 'Inglés', 2016, '', 'Animación', 8.99).
pelicula('Los Increíbles 2', 'La familia de superhéroes regresa en esta secuela, enfrentándose a nuevos desafíos mientras intentan equilibrar sus vidas normales con sus habilidades sobrehumanas.', 'Craig T. Nelson, Holly Hunter, Sarah Vowell.', 118, 'Inglés', 2018, '', 'Animación', 9.99).
pelicula('Coco', 'Miguel, un niño aspirante a músico, se embarca en una extraordinaria aventura en la Tierra de los Muertos para desentrañar los secretos de su familia y cumplir su sueño.', 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt.', 105, 'Inglés', 2017, '', 'Animación', 11.99).
pelicula('Moana', 'Moana, una valiente joven polinesia, se embarca en una peligrosa travesía en el océano para salvar a su pueblo y descubrir su verdadera identidad.', 'Aulii Cravalho, Dwayne Johnson, Rachel House.', 107, 'Inglés', 2016, '', 'Animación', 9.99).
pelicula('Cómo entrenar a tu dragón', 'Hipo, un joven vikingo, se hace amigo de un dragón y juntos desafían las tradiciones de sus respectivas especies en busca de la convivencia pacífica.', 'Jay Baruchel, Gerard Butler, America Ferrera.', 98, 'Inglés', 2010, '', 'Animación', 8.99).
pelicula('Kung Fu Panda', 'Po, un torpe y glotón panda, se convierte en el elegido para convertirse en el Guerrero Dragón y defender el Valle de la Paz del malvado Tai Lung.', 'Jack Black, Dustin Hoffman, Angelina Jolie.', 92, 'Inglés', 2008, '', 'Animación', 7.99).
pelicula('Shrek', 'Shrek, un ogro gruñón, se embarca en una misión para rescatar a la princesa Fiona y en el camino descubre el verdadero significado del amor y la amistad.', 'Mike Myers, Eddie Murphy, Cameron Diaz.', 90, 'Inglés', 2001, '', 'Animación', 6.99).

pelicula('Indiana Jones y los cazadores del arca perdida', 'Indiana Jones, un intrépido arqueólogo, se embarca en una peligrosa misión para encontrar el Arca de la Alianza antes de que caiga en manos equivocadas.', 'Harrison Ford, Karen Allen, Paul Freeman.', 115, 'Inglés', 1981, '', 'Aventura', 9.99).
pelicula('Piratas del Caribe: La maldición del Perla Negra', 'El capitán Jack Sparrow y el joven herrero Will Turner se unen para rescatar a la hija del gobernador y enfrentarse a los temibles piratas que buscan deshacer una maldición.', 'Johnny Depp, Orlando Bloom, Keira Knightley.', 143, 'Inglés', 2003, '', 'Aventura', 8.99).
pelicula('Jurassic Park', 'Un grupo de científicos es invitado a un parque temático habitado por dinosaurios reales, pero pronto descubren que las cosas no saldrán como esperaban.', 'Sam Neill, Laura Dern, Jeff Goldblum.', 127, 'Inglés', 1993, '', 'Aventura', 7.99).
pelicula('El Señor de los Anillos: La Comunidad del Anillo', 'Frodo Baggins, un hobbit, se embarca en un peligroso viaje para destruir un anillo maligno y salvar a la Tierra Media de la oscuridad.', 'Elijah Wood, Ian McKellen, Viggo Mortensen.', 178, 'Inglés', 2001, '', 'Aventura', 10.99).
pelicula('Los Goonies', 'Un grupo de amigos descubre un antiguo mapa del tesoro y se embarca en una emocionante aventura para encontrar el tesoro y salvar sus hogares de la demolición.', 'Sean Astin, Josh Brolin, Corey Feldman.', 114, 'Inglés', 1985, '', 'Aventura', 6.99).
pelicula('El Hobbit: Un viaje inesperado', 'Bilbo Bolsón, un hobbit pacífico, se une a un grupo de enanos y al mago Gandalf en una peligrosa búsqueda para recuperar un reino perdido de los enanos.', 'Martin Freeman, Ian McKellen, Richard Armitage.', 169, 'Inglés', 2012, '', 'Aventura', 9.99).
pelicula('Mad Max: Fury Road', 'En un mundo postapocalíptico, Max Rockatansky y Furiosa se unen en una frenética persecución para salvar a un grupo de mujeres de las garras de un tirano despiadado.', 'Tom Hardy, Charlize Theron, Nicholas Hoult.', 120, 'Inglés', 2015, '', 'Aventura', 8.99).
pelicula('La búsqueda', 'Un arqueólogo y su hijo se embarcan en una búsqueda para encontrar un tesoro oculto y desentrañar los enigmas dejados por los Padres Fundadores de Estados Unidos.', 'Nicolas Cage, Diane Kruger, Justin Bartha.', 131, 'Inglés', 2004, '', 'Aventura', 7.99).
pelicula('Avatar', 'Un veterano de guerra parapléjico es enviado a Pandora, un planeta habitado por una raza indígena y exuberante vida vegetal, donde se ve involucrado en un conflicto épico.', 'Sam Worthington, Zoe Saldana, Sigourney Weaver.', 162, 'Inglés', 2009, '', 'Aventura', 11.99).
pelicula('King Kong', 'Un cineasta y su equipo viajan a una isla remota donde encuentran a King Kong, una criatura gigante que se enamora de una joven y desata el caos en Nueva York.', 'Naomi Watts, Jack Black, Adrien Brody.', 187, 'Inglés', 2005, '', 'Aventura', 9.99).

pelicula('El Conjuro 3: El Diablo Me Obligó a Hacerlo', 'El matrimonio Warren investiga un caso de posesión demoníaca que termina en un asesinato.', 'Vera Farmiga, Patrick Wilson, Ruairi OConnor', 112, 'Inglés', 2021, '', 'Terror', 4.99).
pelicula('Un Lugar en Silencio 2', 'La familia Abbott ahora debe enfrentar los terrores del mundo exterior mientras luchan por sobrevivir en silencio.', 'Emily Blunt, Cillian Murphy, Millicent Simmonds', 97, 'Inglés', 2021, '', 'Terror', 4.99).
pelicula('El Exorcista', 'Una niña poseída por una entidad demoníaca lleva a un sacerdote a enfrentarse a su fe y a luchar contra el mal para salvarla.', 'Linda Blair, Ellen Burstyn, Max von Sydow.', 122, 'Inglés', 1973, '', 'Terror', 9.99).
pelicula('El Resplandor', 'Un escritor en busca de inspiración se convierte en cuidador de un hotel aislado, pero la presencia maligna del lugar desencadena su descenso a la locura.', 'Jack Nicholson, Shelley Duvall, Danny Lloyd.', 144, 'Inglés', 1980, '', 'Terror', 8.99).
pelicula('El Conjuro', 'Basada en hechos reales, una pareja de investigadores paranormales se enfrenta a una entidad maligna que amenaza a una familia en su hogar.', 'Vera Farmiga, Patrick Wilson, Lili Taylor.', 112, 'Inglés', 2013, '', 'Terror', 7.99).
pelicula('Psicosis', 'Una secretaria en fuga se refugia en un motel regentado por un joven tímido y su dominante madre, desencadenando una serie de eventos aterradores.', 'Anthony Perkins, Janet Leigh, Vera Miles.', 109, 'Inglés', 1960, '', 'Terror', 6.99).
pelicula('El Aro', 'Una periodista investiga una misteriosa cinta de video que supuestamente causa la muerte de quien la ve en siete días.', 'Naomi Watts, Martin Henderson, David Dorfman.', 115, 'Inglés', 2002, '', 'Terror', 7.99).
pelicula('El Exorcismo de Emily Rose', 'Basada en una historia real, un sacerdote se enfrenta a un juicio por homicidio debido a la muerte de una joven durante un exorcismo.', 'Laura Linney, Tom Wilkinson, Jennifer Carpenter.', 119, 'Inglés', 2005, '', 'Terror', 8.99).
pelicula('El Proyecto de la Bruja de Blair', 'Un grupo de estudiantes de cine desaparece mientras investiga la leyenda de una bruja en un bosque, dejando atrás su inquietante material grabado.', 'Heather Donahue, Michael C. Williams, Joshua Leonard.', 81, 'Inglés', 1999, '', 'Terror', 6.99).
pelicula('Actividad Paranormal', 'Una pareja documenta la presencia de fenómenos paranormales en su hogar, desatando una escalada de sucesos aterradores.', 'Katie Featherston, Micah Sloat.', 86, 'Inglés', 2007, '', 'Terror', 6.99).