% pelicula(nombre, sinopsis, actores, duracion, idioma, año, enlaces, categoria, costo_obtencion)

pelicula('Infiltrados Mortales', 'Un agente encubierto debe desmantelar una peligrosa organización criminal desde adentro.', 'Jason Statham, Charlize Theron, Chris Hemsworth', 120, 'Inglés', 2022, '', 'Acción', 4.99).
pelicula('Rápidos y Furiosos 9', 'Dom Toretto lleva una vida tranquila con Letty y su hijo, el pequeño Brian, pero saben que el peligro siempre acecha.', 'Vin Diesel, Michelle Rodriguez, Tyrese Gibson', 145, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('Godzilla vs. Kong', 'Godzilla y Kong, dos de las fuerzas más poderosas de un planeta habitado por aterradoras criaturas, se enfrentan en un espectacular combate que sacude los cimientos de la humanidad.', 'Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall', 113, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('Mortal Kombat', 'Un boxeador fracasado descubre un secreto familiar que lo lleva a un torneo místico llamado Mortal Kombat, donde se encuentra con un grupo de guerreros que luchan hasta la muerte para salvar los reinos del malvado hechicero Shang Tsung.', 'Lewis Tan, Jessica McNamee, Josh Lawson', 110, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('El Escuadrón Suicida', 'Bienvenido al infierno, también conocido como Belle Reve, la prisión con la tasa de mortalidad más alta de los Estados Unidos de América.', 'Margot Robbie, Idris Elba, John Cena', 132, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('La Venganza Implacable', 'Un exagente especial busca vengarse de quienes mataron a su familia.', 'Liam Neeson, Jennifer Garner, Mark Wahlberg', 110, 'Inglés', 2019, '', 'Acción', 3.99).
pelicula('Código de Honor', 'Un soldado de élite se embarca en una misión para desenmascarar una conspiración gubernamental.', 'Vin Diesel, Michelle Rodriguez, Samuel L. Jackson', 115, 'Inglés', 2017, '', 'Acción', 2.99).
pelicula('Operación Encubierta', 'Un grupo de agentes encubiertos debe detener un complot terrorista antes de que sea demasiado tarde.', 'Tom Cruise, Scarlett Johansson, Idris Elba', 125, 'Inglés', 2021, '', 'Acción', 4.99).
pelicula('Misión Peligrosa', 'Un equipo de élite es enviado en una misión suicida para rescatar a un rehén de un poderoso criminal.', 'Dwayne Johnson, Emily Blunt, Tom Hardy', 130, 'Inglés', 2023, '', 'Acción', 3.99).
pelicula('El Hombre Araña: Sin Camino a Casa', 'Peter Parker se encuentra en un aprieto cuando su identidad secreta es revelada.', 'Tom Holland, Zendaya, Benedict Cumberbatch', 130, 'Inglés', 2021, '', 'Acción', 4.99).

pelicula('Frozen II', 'Elsa, Anna, Kristoff, Olaf y Sven se aventuran en lo desconocido del bosque encantado para descubrir la verdad sobre los poderes de Elsa y salvar su reino.', 'Idina Menzel, Kristen Bell, Jonathan Groff.', 103, 'Inglés', 2019, '', 'Animación', 11.99).
pelicula('Toy Story 4', 'Woody y Buzz Lightyear se embarcan en una aventura para rescatar a Forky, un nuevo juguete que se considera a sí mismo como basura.', 'Tom Hanks, Tim Allen, Annie Potts.', 100, 'Inglés', 2019, '', 'Animación', 12.99).
pelicula('Spider-Man: Un nuevo universo', 'El joven Miles Morales se convierte en el nuevo Spider-Man y se une a otros héroes de diferentes universos para detener una amenaza que pone en peligro a todos los mundos.', 'Shameik Moore, Jake Johnson, Hailee Steinfeld.', 117, 'Inglés', 2018, '', 'Animación', 10.99).
pelicula('Zootopia', 'Judy Hopps, una conejita policía, se une a un astuto zorro llamado Nick Wilde para resolver un caso en la metrópolis de animales conocida como Zootopia.', 'Ginnifer Goodwin, Jason Bateman, Idris Elba.', 108, 'Inglés', 2016, '', 'Animación', 8.99).
pelicula('Los Increíbles 2', 'La familia de superhéroes regresa en esta secuela, enfrentándose a nuevos desafíos mientras intentan equilibrar sus vidas normales con sus habilidades sobrehumanas.', 'Craig T. Nelson, Holly Hunter, Sarah Vowell.', 118, 'Inglés', 2018, '', 'Animación', 9.99).
pelicula('Coco', 'Miguel, un niño aspirante a músico, se embarca en una extraordinaria aventura en la Tierra de los Muertos para desentrañar los secretos de su familia y cumplir su sueño.', 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt.', 105, 'Inglés', 2017, '', 'Animación', 11.99).
pelicula('Moana', 'Moana, una valiente joven polinesia, se embarca en una peligrosa travesía en el océano para salvar a su pueblo y descubrir su verdadera identidad.', 'Aulii Cravalho, Dwayne Johnson, Rachel House.', 107, 'Inglés', 2016, '', 'Animación', 9.99).
pelicula('Cómo entrenar a tu dragón', 'Hipo, un joven vikingo, se hace amigo de un dragón y juntos desafían las tradiciones de sus respectivas especies en busca de la convivencia pacífica.', 'Jay Baruchel, Gerard Butler, America Ferrera.', 98, 'Inglés', 2010, '', 'Animación', 8.99).
pelicula('Kung Fu Panda', 'Po, un torpe y glotón panda, se convierte en el elegido para convertirse en el Guerrero Dragón y defender el Valle de la Paz del malvado Tai Lung.', 'Jack Black, Dustin Hoffman, Angelina Jolie.', 92, 'Inglés', 2008, '', 'Animación', 7.99).
pelicula('Shrek', 'Shrek, un ogro gruñón, se embarca en una misión para rescatar a la princesa Fiona y en el camino descubre el verdadero significado del amor y la amistad.', 'Mike Myers, Eddie Murphy, Cameron Diaz.', 90, 'Inglés', 2001, '', 'Animación', 6.99).

pelicula('Indiana Jones y los cazadores del arca perdida', 'Indiana Jones, un intrépido arqueólogo, se embarca en una peligrosa misión para encontrar el Arca de la Alianza antes de que caiga en manos equivocadas.', 'Harrison Ford, Karen Allen, Paul Freeman.', 115, 'Inglés', 1981, '', 'Aventura', 9.99).
pelicula('Piratas del Caribe: La maldición del Perla Negra', 'El capitán Jack Sparrow y el joven herrero Will Turner se unen para rescatar a la hija del gobernador y enfrentarse a los temibles piratas que buscan deshacer una maldición.', 'Johnny Depp, Orlando Bloom, Keira Knightley.', 143, 'Inglés', 2003, '', 'Aventura', 8.99).
pelicula('Jurassic Park', 'Un grupo de científicos es invitado a un parque temático habitado por dinosaurios reales, pero pronto descubren que las cosas no saldrán como esperaban.', 'Sam Neill, Laura Dern, Jeff Goldblum.', 127, 'Inglés', 1993, '', 'Aventura', 7.99).
pelicula('El Señor de los Anillos: La Comunidad del Anillo', 'Frodo Baggins, un hobbit, se embarca en un peligroso viaje para destruir un anillo maligno y salvar a la Tierra Media de la oscuridad.', 'Elijah Wood, Ian McKellen, Viggo Mortensen.', 178, 'Inglés', 2001, '', 'Aventura', 10.99).
pelicula('Los Goonies', 'Un grupo de amigos descubre un antiguo mapa del tesoro y se embarca en una emocionante aventura para encontrar el tesoro y salvar sus hogares de la demolición.', 'Sean Astin, Josh Brolin, Corey Feldman.', 114, 'Inglés', 1985, '', 'Aventura', 6.99).
pelicula('El Hobbit: Un viaje inesperado', 'Bilbo Bolsón, un hobbit pacífico, se une a un grupo de enanos y al mago Gandalf en una peligrosa búsqueda para recuperar un reino perdido de los enanos.', 'Martin Freeman, Ian McKellen, Richard Armitage.', 169, 'Inglés', 2012, '', 'Aventura', 9.99).
pelicula('Mad Max: Fury Road', 'En un mundo postapocalíptico, Max Rockatansky y Furiosa se unen en una frenética persecución para salvar a un grupo de mujeres de las garras de un tirano despiadado.', 'Tom Hardy, Charlize Theron, Nicholas Hoult.', 120, 'Inglés', 2015, '', 'Aventura', 8.99).
pelicula('La búsqueda', 'Un arqueólogo y su hijo se embarcan en una búsqueda para encontrar un tesoro oculto y desentrañar los enigmas dejados por los Padres Fundadores de Estados Unidos.', 'Nicolas Cage, Diane Kruger, Justin Bartha.', 131, 'Inglés', 2004, '', 'Aventura', 7.99).
pelicula('Avatar', 'Un veterano de guerra parapléjico es enviado a Pandora, un planeta habitado por una raza indígena y exuberante vida vegetal, donde se ve involucrado en un conflicto épico.', 'Sam Worthington, Zoe Saldana, Sigourney Weaver.', 162, 'Inglés', 2009, '', 'Aventura', 11.99).
pelicula('King Kong', 'Un cineasta y su equipo viajan a una isla remota donde encuentran a King Kong, una criatura gigante que se enamora de una joven y desata el caos en Nueva York.', 'Naomi Watts, Jack Black, Adrien Brody.', 187, 'Inglés', 2005, '', 'Aventura', 9.99).

pelicula('El Conjuro 3: El Diablo Me Obligó a Hacerlo', 'El matrimonio Warren investiga un caso de posesión demoníaca que termina en un asesinato.', 'Vera Farmiga, Patrick Wilson, Ruairi OConnor', 112, 'Inglés', 2021, '', 'Terror', 4.99).
pelicula('Un Lugar en Silencio 2', 'La familia Abbott ahora debe enfrentar los terrores del mundo exterior mientras luchan por sobrevivir en silencio.', 'Emily Blunt, Cillian Murphy, Millicent Simmonds', 97, 'Inglés', 2021, '', 'Terror', 4.99).
pelicula('El Exorcista', 'Una niña poseída por una entidad demoníaca lleva a un sacerdote a enfrentarse a su fe y a luchar contra el mal para salvarla.', 'Linda Blair, Ellen Burstyn, Max von Sydow.', 122, 'Inglés', 1973, '', 'Terror', 9.99).
pelicula('El Resplandor', 'Un escritor en busca de inspiración se convierte en cuidador de un hotel aislado, pero la presencia maligna del lugar desencadena su descenso a la locura.', 'Jack Nicholson, Shelley Duvall, Danny Lloyd.', 144, 'Inglés', 1980, '', 'Terror', 8.99).
pelicula('El Conjuro', 'Basada en hechos reales, una pareja de investigadores paranormales se enfrenta a una entidad maligna que amenaza a una familia en su hogar.', 'Vera Farmiga, Patrick Wilson, Lili Taylor.', 112, 'Inglés', 2013, '', 'Terror', 7.99).
pelicula('Psicosis', 'Una secretaria en fuga se refugia en un motel regentado por un joven tímido y su dominante madre, desencadenando una serie de eventos aterradores.', 'Anthony Perkins, Janet Leigh, Vera Miles.', 109, 'Inglés', 1960, '', 'Terror', 6.99).
pelicula('El Aro', 'Una periodista investiga una misteriosa cinta de video que supuestamente causa la muerte de quien la ve en siete días.', 'Naomi Watts, Martin Henderson, David Dorfman.', 115, 'Inglés', 2002, '', 'Terror', 7.99).
pelicula('El Exorcismo de Emily Rose', 'Basada en una historia real, un sacerdote se enfrenta a un juicio por homicidio debido a la muerte de una joven durante un exorcismo.', 'Laura Linney, Tom Wilkinson, Jennifer Carpenter.', 119, 'Inglés', 2005, '', 'Terror', 8.99).
pelicula('El Proyecto de la Bruja de Blair', 'Un grupo de estudiantes de cine desaparece mientras investiga la leyenda de una bruja en un bosque, dejando atrás su inquietante material grabado.', 'Heather Donahue, Michael C. Williams, Joshua Leonard.', 81, 'Inglés', 1999, '', 'Terror', 6.99).
pelicula('Actividad Paranormal', 'Una pareja documenta la presencia de fenómenos paranormales en su hogar, desatando una escalada de sucesos aterradores.', 'Katie Featherston, Micah Sloat.', 86, 'Inglés', 2007, '', 'Terror', 6.99).

pelicula('Loco por Mary', 'Un hombre se embarca en un viaje desastroso para encontrar a su amor de la escuela secundaria y se encuentra enredado en situaciones hilarantes y absurdas.', 'Ben Stiller, Cameron Diaz, Matt Dillon.', 119, 'Inglés', 1998, '', 'Comedia', 6.99).
pelicula('Superbad', 'Dos amigos adolescentes se embarcan en una misión épica para comprar alcohol y conquistar a las chicas de sus sueños antes de graduarse de la escuela secundaria.', 'Jonah Hill, Michael Cera, Christopher Mintz-Plasse.', 113, 'Inglés', 2007, '', 'Comedia', 7.99).
pelicula('Chicas pesadas', 'Una joven ingenua se infiltra en un grupo popular de chicas de la escuela secundaria y descubre los desafíos y la crueldad de la jerarquía social.', 'Lindsay Lohan, Rachel McAdams, Tina Fey.', 97, 'Inglés', 2004, '', 'Comedia', 6.99).
pelicula('El Gran Lebowski', 'Un hombre llamado "El Nota" se ve envuelto en una serie de eventos extraños y cómicos después de que lo confunden con un millonario del mismo nombre.', 'Jeff Bridges, John Goodman, Julianne Moore.', 117, 'Inglés', 1998, '', 'Comedia', 8.99).
pelicula('Zoolander', 'Un famoso modelo masculino es reclutado para detener a un grupo de conspiradores que planean asesinar al Primer Ministro de Malasia.', 'Ben Stiller, Owen Wilson, Will Ferrell.', 90, 'Inglés', 2001, '', 'Comedia', 7.99).
pelicula('El Diario de Bridget Jones', 'Una mujer en sus 30 años busca el amor y lucha contra los desafíos de la vida mientras registra sus experiencias en su diario personal.', 'Renée Zellweger, Colin Firth, Hugh Grant.', 97, 'Inglés', 2001, '', 'Comedia', 6.99).
pelicula('La Máscara', 'Un hombre tímido encuentra una máscara mágica que lo transforma en un ser con habilidades increíbles, pero también desata su lado más salvaje.', 'Jim Carrey, Cameron Diaz, Peter Riegert.', 101, 'Inglés', 1994, '', 'Comedia', 8.99).
pelicula('Resacón en Las Vegas', 'Después de una noche de fiesta desenfrenada en Las Vegas, un grupo de amigos despierta sin recordar lo sucedido y deben reconstruir los eventos caóticos.', 'Bradley Cooper, Ed Helms, Zach Galifianakis.', 100, 'Inglés', 2009, '', 'Comedia', 7.99).
pelicula('Amelie', 'Una joven inocente y soñadora se embarca en una misión para mejorar la vida de las personas que la rodean mientras busca su propia felicidad.', 'Audrey Tautou, Mathieu Kassovitz, Rufus.', 122, 'Inglés', 2001, '', 'Comedia', 9.99).
pelicula('¡Olvidate de mi!', 'Después de una dolorosa ruptura, un hombre decide borrar todos los recuerdos de su exnovia, pero descubre que algunos recuerdos son difíciles de olvidar.', 'Jim Carrey, Kate Winslet, Kirsten Dunst.', 122, 'Inglés', 2004, '', 'Comedia', 7.99).

pelicula('El Padrino', 'El hijo de un poderoso jefe de la mafia se ve obligado a tomar las riendas de la familia criminal después de un intento de asesinato.', 'Marlon Brando, Al Pacino, James Caan.', 177, 'Inglés', 1972, '', 'Drama', 9.99).
pelicula('El Padrino II', 'El hijo de un poderoso jefe de la mafia se ve obligado a tomar las riendas de la familia criminal después de un intento de asesinato.', 'Al Pacino, Robert De Niro, Robert Duvall.', 202, 'Inglés', 1974, '', 'Drama', 9.99).
pelicula('El Padrino III', 'Un jefe de la mafia retirado se ve obligado a volver a la vida criminal para proteger a su familia de sus enemigos.', 'Al Pacino, Diane Keaton, Andy García.', 170, 'Inglés', 1990, '', 'Drama', 9.99).
pelicula('Titanic', 'Un joven artista y una mujer de clase alta se enamoran a bordo del Titanic, pero su romance se ve amenazado por el trágico destino del barco.', 'Leonardo DiCaprio, Kate Winslet, Billy Zane.', 194, 'Inglés', 1997, '', 'Drama', 9.99).
pelicula('El Renacido', 'Un trampero herido es abandonado por su equipo después de ser atacado por un oso, y se embarca en una odisea de venganza a través del desierto helado.', 'Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson.', 156, 'Inglés', 2015, '', 'Drama', 7.99).
pelicula('La Lista de Schindler', 'Durante la Segunda Guerra Mundial, un empresario alemán salva a más de mil judíos polacos de los campos de concentración nazis.', 'Liam Neeson, Ben Kingsley, Ralph Fiennes.', 195, 'Inglés, Alemán, Hebreo, Polaco', 1993, '', 'Drama', 8.99).
pelicula('El Club de la Pelea', 'Un hombre aburrido y desilusionado forma un club de pelea clandestino como una forma de escape, pero pronto se ve atrapado en una espiral violenta y caótica.', 'Brad Pitt, Edward Norton, Helena Bonham Carter.', 139, 'Inglés', 1999, '', 'Drama', 7.99).
pelicula('Forrest Gump', 'La vida extraordinaria de Forrest Gump, un hombre de inteligencia limitada pero con un corazón puro, quien se encuentra involucrado en importantes eventos históricos.', 'Tom Hanks, Robin Wright, Gary Sinise.', 142, 'Inglés', 1994, '', 'Drama', 9.99).
pelicula('El Silencio de los Corderos', 'Una joven agente del FBI busca la ayuda de un peligroso asesino en serie encarcelado para atrapar a otro asesino en serie que está aterrorizando al país.', 'Jodie Foster, Anthony Hopkins, Scott Glenn.', 118, 'Inglés', 1991, '', 'Drama', 8.99).
pelicula('La Vida es Bella', 'Un padre amoroso utiliza su imaginación y humor para proteger a su hijo de los horrores de un campo de concentración durante el Holocausto.', 'Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini.', 116, 'Italiano', 1997, '', 'Drama', 7.99).

pelicula('Orgullo y Prejuicio', 'En la Inglaterra del siglo XIX, una joven inteligente y enérgica se debate entre el amor y las convenciones sociales cuando conoce a un apuesto y enigmático caballero.', 'Keira Knightley, Matthew Macfadyen, Donald Sutherland.', 129, 'Inglés', 2005, '', 'Romance', 7.99).
pelicula('Titanic', 'Un joven artista y una mujer de clase alta se enamoran a bordo del Titanic, pero su romance se ve amenazado por el trágico destino del barco.', 'Leonardo DiCaprio, Kate Winslet, Billy Zane.', 194, 'Inglés', 1997, '', 'Romance', 9.99).
pelicula('Romeo y Julieta', 'La legendaria historia de amor entre dos jóvenes de familias enemigas, cuyo amor prohibido desencadena una serie de trágicos acontecimientos.', 'Leonardo DiCaprio, Claire Danes, John Leguizamo.', 120, 'Inglés', 1996, '', 'Romance', 8.99).
pelicula('La La Land', 'Un pianista y una aspirante a actriz se enamoran en Los Ángeles mientras persiguen sus sueños en una ciudad llena de esperanzas y desilusiones.', 'Ryan Gosling, Emma Stone, John Legend.', 128, 'Inglés', 2016, '', 'Romance', 7.99).
pelicula('Diario de una Pasión', 'Una historia de amor eterno entre un joven humilde y una joven adinerada en la década de 1940, que se enfrenta a obstáculos y desafíos a lo largo de los años.', 'Ryan Gosling, Rachel McAdams, James Garner.', 123, 'Inglés', 2004, '', 'Romance', 6.99).
pelicula('Bajo la Misma Estrella', 'Dos adolescentes con enfermedades terminales se conocen y se enamoran, viviendo momentos intensos y emotivos mientras enfrentan los desafíos de la vida y la muerte.', 'Shailene Woodley, Ansel Elgort, Nat Wolff.', 126, 'Inglés', 2014, '', 'Romance', 7.99).
pelicula('Casablanca', 'En la Casablanca ocupada por los nazis durante la Segunda Guerra Mundial, un antiguo amante se reencuentra con un hombre que ahora debe elegir entre el amor y el deber.', 'Humphrey Bogart, Ingrid Bergman, Paul Henreid.', 102, 'Inglés', 1942, '', 'Romance', 8.99).
pelicula('El Cuaderno de Noah', 'Una pareja de jóvenes se enamora durante el verano, pero son separados por circunstancias adversas. Años más tarde, se reencuentran y el amor resurge.', 'Ryan Gosling, Rachel McAdams, James Garner.', 123, 'Inglés', 2004, '', 'Romance', 7.99).
pelicula('Antes del Amanecer', 'Dos jóvenes se conocen en un tren y deciden pasar un día juntos en Viena, compartiendo conversaciones profundas y descubriendo una conexión especial.', 'Ethan Hawke, Julie Delpy.', 101, 'Inglés', 1995, '', 'Romance', 6.99).
pelicula('Crepúsculo', 'Una adolescente se enamora de un misterioso y atractivo vampiro, desencadenando una historia de amor prohibido entre dos mundos diferentes.', 'Kristen Stewart, Robert Pattinson, Taylor Lautner.', 122, 'Inglés', 2008, '', 'Romance', 9.99).

pelicula('El Señor de los Anillos: El Retorno del Rey', 'Los ejércitos de Sauron han atacado Minas Tirith, la capital de Gondor. Ahora, el destino de la Tierra Media está en manos de dos pequeños hobbits.', 'Elijah Wood, Viggo Mortensen, Ian McKellen.', 201, 'Inglés', 2003, '', 'Fantasía', 9.99).
pelicula('El Señor de los Anillos: La Comunidad del Anillo', 'Un hobbit de la Comarca y ocho compañeros emprenden un viaje para destruir el poderoso Anillo Único y salvar la Tierra Media del Señor Oscuro Sauron.', 'Elijah Wood, Ian McKellen, Orlando Bloom.', 178, 'Inglés', 2001, '', 'Fantasía', 9.99).
pelicula('El Señor de los Anillos: Las Dos Torres', 'Frodo y Sam continúan su viaje hacia Mordor para destruir el Anillo Único. Mientras tanto, Aragorn y sus compañeros se preparan para la batalla contra las fuerzas de Sauron.', 'Elijah Wood, Ian McKellen, Viggo Mortensen.', 179, 'Inglés', 2002, '', 'Fantasía', 9.99).
pelicula('Harry Potter y la Piedra Filosofal', 'Un niño huérfano es aceptado en la Escuela de Magia y Hechicería de Hogwarts, donde se hace amigo de un joven y sus dos compañeros, y se enfrenta a un malvado mago.', 'Daniel Radcliffe, Rupert Grint, Richard Harris.', 152, 'Inglés', 2001, '', 'Fantasía', 9.99).
pelicula('Harry Potter y la Cámara Secreta', 'Harry ignora las advertencias de un elfo doméstico y regresa a Hogwarts para comenzar su segundo año. Allí, descubre que la Cámara de los Secretos ha sido abierta.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 161, 'Inglés', 2002, '', 'Fantasía', 9.99).
pelicula('Harry Potter y el Prisionero de Azkaban', 'Harry Potter debe enfrentarse a un peligroso fugitivo y a los Dementores, guardianes de la prisión de Azkaban, pero también descubre una gran verdad sobre su pasado.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 142, 'Inglés', 2004, '', 'Fantasía', 9.99).
pelicula('Harry Potter y el Cáliz de Fuego', 'Harry Potter se enfrenta a un dragón, a un mago oscuro y a un laberinto mágico, pero su mayor desafío es la Copa de los Tres Magos.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 157, 'Inglés', 2005, '', 'Fantasía', 9.99).
pelicula('Harry Potter y la Orden del Fénix', 'Harry Potter se enfrenta a un peligroso mago que ha regresado de entre los muertos y está decidido a dominar el mundo mágico.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 139, 'Inglés', 2007, '', 'Fantasía', 9.99).
pelicula('Harry Potter y el Misterio del Príncipe', 'Harry Potter y Dumbledore intentan descubrir la razón por la que Voldemort quiere encontrar la varita del poderoso mago Grindelwald.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 153, 'Inglés', 2009, '', 'Fantasía', 9.99).
pelicula('Harry Potter y las Reliquias de la Muerte: Parte 1', 'Harry, Ron y Hermione deben encontrar los Horrocruxes restantes de Voldemort para poner fin a su reinado de terror.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 146, 'Inglés', 2010, '', 'Fantasía', 9.99).
pelicula('Harry Potter y las Reliquias de la Muerte: Parte 2', 'Harry, Ron y Hermione continúan su búsqueda para encontrar y destruir los Horrocruxes de Voldemort, pero cuando Voldemort descubre sus planes, la batalla final comienza.', 'Daniel Radcliffe, Rupert Grint, Emma Watson.', 130, 'Inglés', 2011, '', 'Fantasía', 9.99).
pelicula('El Hobbit: Un Viaje Inesperado', 'Bilbo Bolsón, un hobbit pacífico, se une a un grupo de enanos para recuperar su tesoro de las garras de un dragón.', 'Martin Freeman, Ian McKellen, Richard Armitage.', 169, 'Inglés', 2012, '', 'Fantasía', 9.99).
pelicula('El Hobbit: La Desolación de Smaug', 'Bilbo y los enanos continúan su búsqueda para recuperar su tesoro de las garras del dragón Smaug.', 'Martin Freeman, Ian McKellen, Richard Armitage.', 161, 'Inglés', 2013, '', 'Fantasía', 9.99).
pelicula('El Hobbit: La Batalla de los Cinco Ejércitos', 'Bilbo y los enanos se enfrentan a Smaug, mientras que otro ejército se acerca a Erebor.', 'Martin Freeman, Ian McKellen, Richard Armitage.', 144, 'Inglés', 2014, '', 'Fantasía', 9.99).